# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application CI

on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
        - main

#permissions:
  #contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    # step1 check out the code repository
    steps:
    - name: check out the code 
      uses: actions/checkout@v2
      
    # step2 setup python environment 
    -  name: Setup Python
       uses: actions/setup-python@v2
       with:
          python-version: 'python-latest'
    # step3: install dependencies 
    -  name: Install dependencies
       run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #step4: run tests
    -  name: Run tests
       run: pytest
